/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'mainCourse' : IDL.Null,
  'dessert' : IDL.Null,
  'appetizer' : IDL.Null,
  'beverage' : IDL.Null,
});
export const MenuItemId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : Category,
  'price' : IDL.Float64,
});
export const UpiSettings = IDL.Record({
  'merchantName' : IDL.Text,
  'qrCodeData' : IDL.Text,
  'upiId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, Category, IDL.Opt(IDL.Text)],
      [MenuItemId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getUpiSettings' : IDL.Func([], [IDL.Opt(UpiSettings)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'toggleAvailability' : IDL.Func([MenuItemId], [], []),
  'updateMenuItem' : IDL.Func(
      [
        MenuItemId,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        Category,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateUpiSettings' : IDL.Func([UpiSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'mainCourse' : IDL.Null,
    'dessert' : IDL.Null,
    'appetizer' : IDL.Null,
    'beverage' : IDL.Null,
  });
  const MenuItemId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : Category,
    'price' : IDL.Float64,
  });
  const UpiSettings = IDL.Record({
    'merchantName' : IDL.Text,
    'qrCodeData' : IDL.Text,
    'upiId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, Category, IDL.Opt(IDL.Text)],
        [MenuItemId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getUpiSettings' : IDL.Func([], [IDL.Opt(UpiSettings)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'toggleAvailability' : IDL.Func([MenuItemId], [], []),
    'updateMenuItem' : IDL.Func(
        [
          MenuItemId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          Category,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateUpiSettings' : IDL.Func([UpiSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };